version: '3'

services:
  redis:
    image: "redis:6.2.3"
    hostname: redis
    networks:
      - tdm
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  postgres:
    image: "ridler17/tdm-db-postgresql:latest"
    tty: true
    environment:
      - TDM_DB_USER=${TDM_DB_USER:-tdm}
      - TDM_DB_PASSWORD=${TDM_DB_PASSWORD:-pa55w0rd}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgrespa55w0rd}
    ports:
      - "${TDM_POSTGRES_PORT:-5432}:5432"
    hostname: postgres
    healthcheck:
      test: ["CMD", "etc/healthcheck.sh"]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - tdm
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    networks:
      - tdm
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 20s
      timeout: 30s
      retries: 3
    volumes:
      - ./rabbitconf:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=/

  swagger_ui:
    image: "swaggerapi/swagger-ui"
    tty: true
    environment:
      BASE_URL: /openapi
      URL: http://${TDM_HOSTNAME}:${TDM_PORT:-80}/v1/docs/openapi.json
    hostname: swagger_ui
    networks:
      - tdm
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/openapi/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  tdm_api:
    image: "ridler17/tdm-api:latest"
    tty: true
    environment:
      - TDM_FERNET_KEY=${TDM_FERNET_KEY:-F94ALRGQKFqYQqc-LveNA4uSjxLwI0qmZRzfzMc6qME=}
      - TDM_APPLICATION_KEY=${TDM_APPLICATION_KEY:-594df9ea-3565-4145-b9c4-9bbc47ff6200}
      - TDM_DB_USER=${TDM_DB_USER:-tdm}
      - TDM_DB_PASSWORD=${TDM_DB_PASSWORD:-pa55w0rd}
      - TDM_ADMIN_USERNAME=${TDM_ADMIN_USERNAME:-admin}
      - TDM_ADMIN_PASSWORD=${TDM_ADMIN_PASSWORD:-pa55w0rd}
      - TDM_ADMIN_EMAIL=${TDM_ADMIN_EMAIL:-admin@companyname.com}
      - TDM_RABBIT_MQ_USER=${TDM_RABBIT_MQ_USER:-tdm}
      - TDM_RABBIT_MQ_PASSWORD=${TDM_RABBIT_MQ_PASSWORD:-pa55w0rd}
      - TDM_SPARK_SSH_USER=${TDM_SPARK_SSH_USER:-tdm}
      - TDM_SPARK_SSH_PASSWORD=${TDM_SPARK_SSH_PASSWORD:-pa55w0rd}
      - TDM_SPARK_SSH_HOST=spark
      - TDM_SPARK_SSH_PORT=22
      - TDM_LOG_LEVEL=${TDM_LOG_LEVEL:-DEBUG}
      - TDM_URL=http://${TDM_HOSTNAME}:${TDM_PORT:-80}/v1/
      - TDM_PORT=${TDM_PORT:-80}
      - TDM_HOSTNAME=${TDM_HOSTNAME}
    networks:
      - tdm
    hostname: tdm_api
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://tdm-nginx/v1/versions || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - csv_vol:/tdm_api/csv
      - jars:/tdm_api/lib
      - jsons:/var/configurations/
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  tdm_ui:
    image: "ridler17/tdm-ui:latest"
    tty: true
    environment:
      - TDM_APPLICATION_KEY=${TDM_APPLICATION_KEY:-594df9ea-3565-4145-b9c4-9bbc47ff6200}
    networks:
      - tdm
    restart: unless-stopped
    links:
      - "tdm_api:backend"
      - "tdm-docs:docs"
    depends_on:
      - "tdm_api"
    hostname: tdm_ui
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://tdm_ui:32080/#login || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  spark:
    image: "ridler17/tdm-spark:latest"
    tty: true
    environment:
        - TDM_SPARK_SSH_USER=${TDM_SPARK_SSH_USER:-tdm}
        - TDM_SPARK_SSH_PASSWORD=${TDM_SPARK_SSH_PASSWORD:-pa55w0rd}
        - TDM_SPARK_MASTER_URL=spark://localhost:7077 # for standalone cluster
        - SPARK_WORKER_INSTANCES=2
    networks:
      - tdm
    restart: unless-stopped
    hostname: localhost
    volumes:
      - spark-events:/tmp/spark-events
      - spark-logs:/tmp/spark-logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  tdm-docs:
    image: "ridler17/tdm-docs:latest"
    tty: true
    networks:
      - tdm
    restart: unless-stopped
    hostname: docs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://docs:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  tdm-ssh:
    image: tdm-ssh:latest
    hostname: tdm_ssh
    environment:
      - TDM_FERNET_KEY=${TDM_FERNET_KEY:-F94ALRGQKFqYQqc-LveNA4uSjxLwI0qmZRzfzMc6qME=}
    networks:
      - tdm
    ports:
      - 5050:5050
    restart: always
    volumes:
      - jsons:/var/configurations/
      - jars:/tdm_ssh/jars

  tdm-nginx:
    image: "ridler17/tdm-nginx:latest"
    tty: true
    environment:
      - TDM_APPLICATION_KEY=${TDM_APPLICATION_KEY:-594df9ea-3565-4145-b9c4-9bbc47ff6200}
    networks:
      - tdm
    hostname: tdm-nginx
    restart: always
    ports:
      - ${TDM_PORT:-80}:80
      - ${SPARK_UI_PORT:-8080}:8080
      - ${SPARK_HISTORY_PORT:-18080}:18080
#    volumes:
#      - ./conf:/etc/nginx/conf.d
#      - ./cert:/root/cert
    depends_on:
      - tdm_ui
      - tdm_api
      - tdm-docs
      - spark
#      - tdm-keycloak

volumes:
  postgres:
  spark-events:
  spark-logs:
  csv_vol:
  jsons:
  jars:

networks:
  tdm:
    driver: bridge
